### ISSUE TITLE
poke

### ISSUE THREAD

**Issue by RewAkuto** [PokeRogueMOD/PyPoRoMOD#1]

**Comment by M6D6M6A** [comment]
Im currently not fixing the python api code, since it broke 3x in one day, i will give it some time before waisting time with finding fixes wich will be patched soon. I just moved to making the account editor with a GUI in the browser, today i implemented the new layout and the roll hack, tomorrow i will start with implementing the Achievement Unlocker and maybe more:
- [Inject new GUI](https://github.com/PokeRogueMOD/JsPoRoMOD/blob/main/inject.js)
- [Old GUI with basic Roll and Achievement unlocker](https://github.com/PokeRogueMOD/JsPoRoMOD/blob/main/hack.js)
- [Guide on how to use any of the two versions, i have no Video for the new GUI yet!](https://youtu.be/e-Dvv_VS-kY)

**Comment by M6D6M6A** [comment]
I found a solution, the tool should work again. :)
